# Generated by Django 4.2.4 on 2023-08-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expertize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=122)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='gallery/')),
            ],
            options={
                'verbose_name_plural': 'Galleries',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('slogan', models.CharField(max_length=122)),
                ('image', models.ImageField(upload_to='sliders/')),
            ],
            options={
                'verbose_name_plural': 'Slider',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=122)),
                ('description', models.TextField()),
                ('thumbnail', models.ImageField(upload_to='services/')),
                ('cover', models.ImageField(upload_to='services/')),
                ('image1', models.ImageField(upload_to='services/')),
                ('image2', models.ImageField(upload_to='services/')),
                ('items', models.ManyToManyField(to='hospital.item')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('speciality', models.CharField(max_length=122)),
                ('picture', models.ImageField(upload_to='mentors/')),
                ('detail', models.TextField()),
                ('experience', models.TextField()),
                ('twitter', models.CharField(blank=True, max_length=122, null=True)),
                ('facebook', models.CharField(blank=True, max_length=122, null=True)),
                ('instagram', models.CharField(blank=True, max_length=122, null=True)),
                ('expertize', models.ManyToManyField(related_name='mentor', to='hospital.expertize')),
            ],
        ),
    ]
